# Generated by Django 5.2.1 on 2025-05-13 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Notes',
        ),
    ]
